name: Claude Code Binaries Updater

on:
  # every 2 hours
  schedule:
    - cron: "0 */2 * * *"
  # manually trigger a workflow_dispatch event
  workflow_dispatch:

permissions: write-all

jobs:
  auto-update-gitea:
    runs-on: ubuntu-latest
    if: ${{ contains(github.server_url, 'gitea') }}
    container: catthehacker/ubuntu:act-20.04  # Uncomment it if you use it on Gitea

    env:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      http_proxy: ${{ secrets.HTTP_PROXY }}
      https_proxy: ${{ secrets.HTTPS_PROXY }}

    steps:
      - name: Disable SSL Verify
        run: git config --global http.sslVerify false

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Claude Code Version
        id: version
        run: |
          VERSION=$(./scripts/install_binaries.sh get_version)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Retrieved version: $VERSION"

      - name: Check if Version Exists
        id: check_version
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          if git tag --list | grep -q "^${VERSION}$"; then
            echo "Tag $VERSION already exists"
            echo "tag_exists=true" >> $GITHUB_OUTPUT
          else
            echo "Tag $VERSION does not exist"
            echo "tag_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Install New Version
        if: ${{ steps.check_version.outputs.tag_exists == 'false' }}
        run: |
          chmod +x ./scripts/install_binaries.sh
          ./scripts/install_binaries.sh

      - name: Update Assets
        if: ${{ steps.check_version.outputs.tag_exists == 'false' }}
        uses: akkuman/gitea-release-action@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: ${{ steps.version.outputs.version }}
          body: |
            # Update Claude Code Binary
            ## v${{ steps.version.outputs.version }}
          files: |-
            ./binaries/*/*
            ./build/*

  auto-update-github:
    runs-on: ubuntu-latest
    if: ${{ contains(github.server_url, 'github') }}
    # container: catthehacker/ubuntu:act-20.04  # Uncomment it if you use it on Gitea

    steps:
      - name: Disable SSL Verify
        run: git config --global http.sslVerify false

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Claude Code Version
        id: version
        run: |
          VERSION=$(./scripts/install_binaries.sh get_version)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Retrieved version: $VERSION"

      - name: Check if Version Exists
        id: check_version
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          if git tag --list | grep -q "^${VERSION}$"; then
            echo "Tag $VERSION already exists"
            echo "tag_exists=true" >> $GITHUB_OUTPUT
          else
            echo "Tag $VERSION does not exist"
            echo "tag_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Install New Version
        if: ${{ steps.check_version.outputs.tag_exists == 'false' }}
        run: |
          chmod +x ./scripts/install_binaries.sh
          ./scripts/install_binaries.sh

      - name: Upload Release Assets
        if: ${{ steps.check_version.outputs.tag_exists == 'false' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: ${{ steps.version.outputs.version }}
          body: |
            # Update Claude Code Binary
            ## v${{ steps.version.outputs.version }}
          files: |-
            ./binaries/*/*
            ./build/*
